/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ProjectSidebar: typeof import('./components/todo/ProjectSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskBulkActions: typeof import('./components/todo/TaskBulkActions.vue')['default']
    TaskComposer: typeof import('./components/todo/TaskComposer.vue')['default']
    TaskList: typeof import('./components/todo/TaskList.vue')['default']
    TaskToolbar: typeof import('./components/todo/TaskToolbar.vue')['default']
    TodoHeader: typeof import('./components/todo/TodoHeader.vue')['default']
    TodoInsights: typeof import('./components/todo/TodoInsights.vue')['default']
    TodoWorkspace: typeof import('./components/todo/TodoWorkspace.vue')['default']
    UndoBar: typeof import('./components/todo/UndoBar.vue')['default']
  }
}

// For TSX support
declare global {
  const AAlert: typeof import('ant-design-vue/es')['Alert']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACard: typeof import('ant-design-vue/es')['Card']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const ACol: typeof import('ant-design-vue/es')['Col']
  const AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
  const ADivider: typeof import('ant-design-vue/es')['Divider']
  const AEmpty: typeof import('ant-design-vue/es')['Empty']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
  const ALayout: typeof import('ant-design-vue/es')['Layout']
  const ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
  const ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
  const ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AProgress: typeof import('ant-design-vue/es')['Progress']
  const ARow: typeof import('ant-design-vue/es')['Row']
  const ASelect: typeof import('ant-design-vue/es')['Select']
  const ASpace: typeof import('ant-design-vue/es')['Space']
  const AStatistic: typeof import('ant-design-vue/es')['Statistic']
  const ASwitch: typeof import('ant-design-vue/es')['Switch']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const ATextarea: typeof import('ant-design-vue/es')['Textarea']
  const ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
  const ProjectSidebar: typeof import('./components/todo/ProjectSidebar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TaskBulkActions: typeof import('./components/todo/TaskBulkActions.vue')['default']
  const TaskComposer: typeof import('./components/todo/TaskComposer.vue')['default']
  const TaskList: typeof import('./components/todo/TaskList.vue')['default']
  const TaskToolbar: typeof import('./components/todo/TaskToolbar.vue')['default']
  const TodoHeader: typeof import('./components/todo/TodoHeader.vue')['default']
  const TodoInsights: typeof import('./components/todo/TodoInsights.vue')['default']
  const TodoWorkspace: typeof import('./components/todo/TodoWorkspace.vue')['default']
  const UndoBar: typeof import('./components/todo/UndoBar.vue')['default']
}